version: '2'
services:
  jenkins:
    build: ./docker
    restart: always
    ports:
      - 127.0.0.1:18080:8080
      - 127.0.0.1:50000:50000
    privileged: true
    volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
